<?php
/**
 * Jollof Living — about
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$ssr = SSR::hero(
        'About us',
        'Luxury living, African soul',
        'The story, standards and safeguards behind Nigeria’s premium short-let platform — every home inspected, every payment escrow-protected.',
        url('stays.php'),
        'Browse residences'
    );
View::header('about', ['ssr' => $ssr]);
View::footer();
