<?php
/**
 * Jollof Living — admin-login
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

if (Auth::isAdmin()) {
    redirect($_GET['next'] ?? 'admin.php');
}

View::header('admin-login');
View::footer();
