<?php
/**
 * Jollof Living — admin
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

Auth::requireAdmin();

$extra = [
    'charts' => [
        'revenue' => Repo::revenueSeries(12),
        'byCity'  => Repo::revenueByCity(),
    ],
    'cmsBlocks' => array_map(static fn($b) => [
        'id'     => (int) $b['id'],
        'title'  => $b['title'],
        'body'   => (string) $b['body'],
        'status' => $b['status'],
    ], DB::all('SELECT * FROM cms_blocks ORDER BY id')),
    'campaigns' => array_map(static fn($c) => [
        'id'           => (int) $c['id'],
        'code'         => $c['code'],
        'name'         => $c['name'],
        'window_label' => $c['window_label'],
        'status'       => $c['status'],
    ], DB::all('SELECT * FROM campaigns ORDER BY id')),
    'roles' => array_map(static fn($r) => [
        $r['role'],
        [
            'admin'     => 'Full platform access',
            'host'      => 'Own listings, calendar and payouts',
            'corporate' => 'Business travel portal and invoicing',
            'guest'     => 'Book, review and message',
        ][$r['role']] ?? 'Platform access',
        (int) $r['n'],
    ], DB::all('SELECT role, COUNT(*) AS n FROM users GROUP BY role ORDER BY n DESC')),
];

View::header('admin', ['extra' => $extra]);
View::footer();
