<?php
/**
 * Jollof Living — app
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$ssr = SSR::hero(
        'The app',
        'Your stay, keyless',
        'Keyless check-in, live messaging, wallet passes and voice booking — the full Jollof Living platform in your pocket.',
        url('auth.php'),
        'Create a free account'
    );
View::header('app', ['ssr' => $ssr]);
View::footer();
