<?php
/**
 * Jollof Living — auth
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

// already signed in? go where they were heading
if (Auth::check()) {
    redirect($_GET['next'] ?? 'account.php');
}
$mode = ($_GET['mode'] ?? 'signin') === 'register' ? 'register' : 'signin';

View::header('auth', [
    'title' => $mode === 'register' ? 'Create your account | Jollof Living' : 'Sign in | Jollof Living',
]);
View::footer();
