<?php
/**
 * Jollof Living — blog-post
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$slug = (string) ($_GET['s'] ?? '');
$post = $slug !== '' ? Repo::blogPost($slug) : null;

if (!$post) {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

View::header('blog-' . $post['slug'], [
    'metaKey' => 'blog',
    'title'   => $post['title'] . ' | The Journal — Jollof Living',
    'desc'    => mb_substr(strip_tags((string) $post['excerpt']), 0, 300),
    'image'   => base_path() . '/assets/img/' . (View::images()[$post['img']] ?? 'hero.jpg'),
    'extra'   => ['post' => $post],
]);
View::noscript(
    '<h1>' . e($post['title']) . '</h1>'
    . implode('', array_map(static fn($p) => '<p>' . e($p) . '</p>', $post['body']))
);
View::footer();
