<?php
/**
 * Jollof Living — booking
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$slug = (string) ($_GET['p'] ?? '');
$property = $slug !== '' ? Repo::property($slug) : null;

if (!$property || $property['status'] !== 'live') {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

$extra = [
    'stay'    => $property,
    'blocked' => BookingService::blockedRanges((int) $property['pid']),
];

View::header('booking-' . $property['id'], [
    'metaKey' => 'stays',
    'title'   => 'Complete your reservation — ' . $property['name'] . ' | Jollof Living',
    'desc'    => 'Secure checkout for ' . $property['name'] . ' — split payments, promo codes and escrow protection.',
    'extra'   => $extra,
]);
View::footer();
