<?php
/**
 * Jollof Living — compare
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

Auth::requireLogin();

$ssr = SSR::hero(
        'Compare',
        'Compare residences side by side',
        'Up to three residences at once — pricing, ratings, bedrooms and amenities. Tap Compare on any residence to add it here.',
        url('stays.php'),
        'Choose residences to compare'
    );
View::header('compare', ['ssr' => $ssr]);
View::footer();
