<?php
/**
 * Jollof Living — concierge
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$ssr = SSR::hero(
        'AI concierge',
        'Plan a stay in seconds, 24/7',
        'Ask about stays, prices, itineraries, transfers and private chefs — Jollof, your AI concierge, answers instantly.',
        url('stays.php'),
        'Browse stays'
    )
    . SSR::stayGrid(Repo::properties(true), 3);
View::header('concierge', ['ssr' => $ssr]);
View::footer();
