<?php
/**
 * Jollof Living — confirm
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$ref = (string) ($_GET['ref'] ?? '');
$booking = $ref !== '' ? BookingService::find($ref) : null;

// only the guest who made it (or an admin) may view a reservation
if ($booking && $booking['user_id'] && (int) $booking['user_id'] !== (int) (Auth::id() ?? 0) && !Auth::isAdmin()) {
    $booking = null;
}

if (!$booking) {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

$extra = ['booking' => [
    'ref'          => $booking['ref'],
    'prop'         => $booking['property_slug'],
    'name'         => $booking['property_name'],
    'img'          => $booking['img'],
    'area'         => $booking['area'],
    'city'         => $booking['city'],
    'in'           => $booking['checkin'],
    'out'          => $booking['checkout'],
    'nights'       => (int) $booking['nights'],
    'guests'       => (int) $booking['guests'],
    'method'       => $booking['pay_method'],
    'addons'       => $booking['addons'],
    'split'        => (int) $booking['split_payment'] === 1,
    'req'          => (int) $booking['is_request'] === 1,
    'total'        => (int) $booking['total'],
    'status'       => $booking['status'],
    'code'         => $booking['checkin_code'],
    'pointsEarned' => (int) $booking['points_earned'],
]];

View::header('confirm', ['extra' => $extra]);
View::footer();
