<?php
/**
 * Jollof Living — giftcards
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$ssr = SSR::hero(
        'Gift cards',
        'Give the gift of a Jollof stay',
        'Digital gift cards delivered by email or WhatsApp — they never expire and redeem across every residence.'
    )
    . SSR::secHead('Redeemable on', 'Residences guests love')
    . SSR::stayGrid(Repo::properties(true), 3);
View::header('giftcards', ['ssr' => $ssr]);
View::footer();
