<?php
/**
 * Jollof Living — host-dashboard
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

Auth::requireHost();

View::header('host-dashboard');
View::footer();
