<?php
/**
 * Jollof Living — neighborhood
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$slug = (string) ($_GET['n'] ?? '');
$hood = $slug !== '' ? Repo::neighborhood($slug) : null;

if (!$hood) {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

View::header('neighborhood-' . $hood['id'], [
    'metaKey' => 'neighborhoods',
    'title'   => $hood['name'] . ' — Neighbourhood Guide | Jollof Living',
    'desc'    => mb_substr(strip_tags((string) $hood['desc']), 0, 300),
    'extra'   => ['hood' => $hood],
]);
View::noscript('<h1>' . e($hood['name']) . '</h1><p>' . e((string) $hood['desc']) . '</p>');
View::footer();
