<?php
/**
 * Jollof Living — stay
 * Generated by tools/gen_pages.mjs — edit the generator, not this file.
 */
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
require JL_INC . '/view.php';

$slug = (string) ($_GET['p'] ?? '');
$property = $slug !== '' ? Repo::property($slug) : null;

if (!$property || $property['status'] !== 'live') {
    http_response_code(404);
    View::header('404');
    View::footer();
    exit;
}

Repo::recordView((int) $property['pid']);

$extra = [
    'stay'    => $property,
    'blocked' => BookingService::blockedRanges((int) $property['pid']),
];

View::header('stay-' . $property['id'], [
    'metaKey' => 'stays',
    'title'   => $property['name'] . ' — Luxury Stay | Jollof Living',
    'desc'    => mb_substr(strip_tags((string) $property['desc']), 0, 300),
    'image'   => base_path() . '/assets/img/' . (View::images()[$property['img']] ?? 'hero.jpg'),
    'extra'   => $extra,
]);
View::noscript(
    '<h1>' . e($property['name']) . '</h1>'
    . '<p>' . e((string) $property['area']) . ', ' . e((string) $property['city']) . ' · '
    . e(money((int) $property['price'])) . ' per night · ' . e((string) $property['rating']) . '★ ('
    . (int) $property['reviews'] . ' reviews)</p>'
    . '<p>' . e((string) $property['desc']) . '</p>'
    . '<p><a href="' . e(url('booking.php?p=' . urlencode($property['id']))) . '">Reserve this residence</a></p>'
);
View::footer();
